name: Pack extension
on:
  workflow_dispatch:

jobs:
  package:
    name: Package extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: "."
          zipFilePath: "build/extension.zip"
      - uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: "build/extension.zip"
          crxFilePath: "build/extension.crx"
          privateKey: ${{ secrets.PRIVATE_KEY }}    
      - uses: actions/create-release@v1
        id: create_release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: tagname
          release_name: Release draft
          draft: true
      - uses: actions/upload-release-asset@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/extension.crx
          asset_name: extension.crx
          asset_content_type: application/x-chrome-extension
